# Generated by Django 4.2.2 on 2023-06-09 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_zadaniastale_recipients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
