# Generated by Django 4.2.2 on 2023-06-09 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zadaniastale',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='zadaniastale',
            name='recipients',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
