# Generated by Django 4.2.2 on 2023-06-09 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_remove_zadaniastale_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zadaniastale',
            name='recipients',
        ),
        migrations.AddField(
            model_name='zadaniastale',
            name='recipients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
