# Generated by Django 4.2.2 on 2023-06-09 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_remove_zadaniastale_recipients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadaniastale',
            name='recipients',
            field=models.ForeignKey(limit_choices_to={'email': 'pracownik@mail.com'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
