# Generated by Django 4.2.2 on 2023-06-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_zadaniajednorazowe'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadaniastale',
            name='progress',
            field=models.CharField(choices=[('rozpoczęte', 'Rozpoczęte'), ('zakończone', 'Zakończone')], default='rozpoczęte', max_length=20),
        ),
    ]
