# Generated by Django 4.2.2 on 2023-06-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_zadaniastale_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadaniajednorazowe',
            name='progress',
            field=models.CharField(choices=[('rozpoczęte', 'Rozpoczęte'), ('zakończone', 'Zakończone')], default='rozpoczęte', max_length=20),
        ),
    ]
