# Generated by Django 4.2.2 on 2023-06-10 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_zadaniajednorazowe_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadaniastale',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='zadaniastale',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='zadaniajednorazowe',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
