# Generated by Django 4.2.2 on 2023-06-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_h_zadaniajednorazowe_h_zadaniastale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_zadaniajednorazowe',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='h_zadaniajednorazowe',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='h_zadaniastale',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='h_zadaniastale',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='przydzielonezadaniestale',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='przydzielonezadaniestale',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zadaniajednorazowe',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zadaniajednorazowe',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
